create table tb_endereco (id bigint not null generated by default as identity, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id))
create table tb_estoque (id bigint not null generated by default as identity, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque integer not null, quantidade_minima integer not null, primary key (id))
create table tb_fornecedor (id bigint not null generated by default as identity, cnpj_fornecedor integer not null, data_cadastro date, email varchar(255), hora_cadastro time, nome_fantasia_fornecedor varchar(255), nome_razao_social_fornecedor varchar(255), ramo_atuacao varchar(255), telefone integer not null, endereco_id bigint, primary key (id))
create table tb_funcionario (id bigint generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id bigint, primary key (id))
create table tb_movimentacao (id bigint not null generated by default as identity, data_movimentacao timestamp, quantidade_movimentcaoes integer not null, tipo_movimentacao varchar(255), primary key (id))
create table tb_produto (id bigint not null generated by default as identity, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto integer not null, nome_produto varchar(255), preco_produto double not null, quantidade_produto integer not null, unidade_medida varchar(255), estoque_id bigint, fornecedor_id bigint, movimentacao_id bigint, primary key (id))
create table tb_setor (id bigint generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito integer not null, nome_setor varchar(255), primary key (id))

alter table tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco
alter table tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor
alter table tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque
alter table tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor
alter table tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao



create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id  bigserial not null, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id  bigserial not null, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id int8 generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id int8 generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table if exists tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table if exists tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table if exists tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table if exists tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table if exists tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table if exists tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id int8 generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id int8 generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table if exists tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table if exists tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table if exists tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table if exists tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table if exists tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table if exists tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id int8 generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id int8 generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table if exists tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table if exists tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table if exists tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table if exists tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table if exists tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table if exists tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id int8 generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id int8 generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table if exists tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table if exists tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table if exists tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table if exists tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table if exists tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table if exists tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id int8 generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id int8 generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table if exists tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table if exists tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table if exists tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table if exists tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table if exists tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table if exists tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
create sequence hibernate_sequence start 1 increment 1;
create table tb_endereco (id int8 not null, cep varchar(255), cidade varchar(255), logradouro varchar(255), uf varchar(255), primary key (id));
create table tb_estoque (id int8 not null, data_entrada date, data_saida date, hora_entrada time, hora_saida time, nome_estoque varchar(255), quant_saldo_estoque int4 not null, quantidade_minima int4 not null, primary key (id));
create table tb_fornecedor (id int8 not null, cnpj_fornecedor int8, email varchar(255), nome_fornecedor varchar(255), endereco_id int8, primary key (id));
create table tb_funcionario (id int8 generated by default as identity, email varchar(255), nome_completo varchar(255), telefone varchar(255), setor_id int8, primary key (id));
create table tb_movimentacao (id int8 not null, data_movimentacao timestamp, quantidade_movimentcaoes int4 not null, tipo_movimentacao varchar(255), primary key (id));
create table tb_produto (id int8 not null, data_cadastro timestamp, data_validade date, desc_produto varchar(255), hora_cadastro time, lote_produto int4 not null, nome_produto varchar(255), preco_produto float8 not null, quantidade_produto int4 not null, unidade_medida varchar(255), estoque_id int8, fornecedor_id int8, movimentacao_id int8, primary key (id));
create table tb_setor (id int8 generated by default as identity, andar varchar(255), bloco varchar(255), data_cadastro date, hora_cadastro time, leito int4 not null, nome_setor varchar(255), primary key (id));
create table tb_telefone (id int8 not null, numero int4 not null, tipo varchar(255), fornecedor_id int8, primary key (id));
alter table if exists tb_fornecedor add constraint FK9na31v4u4tf0uqv924dbq4jc5 foreign key (endereco_id) references tb_endereco;
alter table if exists tb_funcionario add constraint FKs8erg8a6ogo3u6hgud9ghokxg foreign key (setor_id) references tb_setor;
alter table if exists tb_produto add constraint FK3y4b2oh0d7f56i2ytgc65ce19 foreign key (estoque_id) references tb_estoque;
alter table if exists tb_produto add constraint FK5ewr4ycyetl83m6eew08otjd7 foreign key (fornecedor_id) references tb_fornecedor;
alter table if exists tb_produto add constraint FKg6304c3kvioo9smqajfey4th6 foreign key (movimentacao_id) references tb_movimentacao;
alter table if exists tb_telefone add constraint FKiox57g0r0u2x1beddr1w0kf5v foreign key (fornecedor_id) references tb_fornecedor;
